[package]
name = "sure"
version = "0.3.0"
edition = "2024"
publish = true

license = "MIT OR Apache-2.0"
repository = "https://github.com/lars-schumann/sure"
# homepage = ""
readme = "README.md"
description = "Refinement types"
keywords = []

[dependencies]

[workspace]
members = ["sure_bench", "sure_run_bench"]
